Add tax code to shipping refund
sdtechdev/solidus_avatax_certified pull request #37
Opened 2020-12-11 12:10 UTC by Makapoxa

Can we please add the correct tax code (in Avalara) to the refund reason 'Refund shipping fee' in Kata. Currently this refund code is not refunding tax.

The tax code should be FR000000, not P0000000. (in Avalara line record)

https://dekeo.atlassian.net/browse/ALPHA-2490

2020-12-14 05:26 UTC, untwal approved these changes

2020-12-14 20:34 UTC, ashishtajane commented on app/models/solidus_avatax_certified/line.rb
> +        tax_code = Spree::TaxCategory.find_by(name: 'Shipping').&tax_code
I don't like it. This is adding our app logic assumption in this code.. can we make it better?

2020-12-15 09:21 UTC, ashishtajane approved these changes

2020-12-15 09:23 UTC, ashishtajane requested changes
The branch should be made from `jiffy-v2.3` and PR should be against this same branch `jiffy-v2.3`

2020-12-16 07:16 UTC, ashishtajane approved these changes

2020-12-16 07:24 UTC, merged